### PR TITLE
issue/2799 Remove redundant behaviour

### PR DESCRIPTION
**Pull request by oliverfoster**
requires https://github.com/adaptlearning/adapt-contrib-core/pull/84
part of https://github.com/adaptlearning/adapt_framework/issues/2799

### Changed
* Use `offlineStorage`, `a11y`, `logging`, `router`, `data` and `notify` directly

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by lc-alexanderbenesch — APPROVED** [review]
👍

**Comment by eleanor-heath** [comment]
there are conflicts in the branch that need resolved

**Review by eleanor-heath — APPROVED** [review]

**Comment by oliverfoster** [comment]
await merge and release of https://github.com/adaptlearning/adapt-contrib-core/pull/84

**Pull request merged**
