### PR TITLE
issue/55 Bypass language picker on lang search param

### LINKED ISSUE #55: Bypass language picker if `lang` search param specified
Alternative fix for https://github.com/adaptlearning/adapt_framework/issues/3227

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #55 

### Fixed
* Added check for `lang` search param

### CODE REVIEW

**Comment by cahirodoherty-learningpool** [comment]
Will this then fall foul of the bad lang params? i.e. non-existent languages

**Comment by oliverfoster** [comment]
Yes, kind of. It'd currently just choose the default language if you put in a bad lang. You'd have to update this pr to show the language picker if lang is missing from availableLanguageNames, if that's what you want instead?

**Comment by oliverfoster** [comment]
Kind of. It'd currently just choose the default language if you put in a bad lang. You'd have to update this pr to show the language picker if lang is missing from availableLanguageNames and that's what you want instead?

**Comment by cahirodoherty-learningpool** [comment]
Hi Oliver, I have created a PR that expands on the behaviour you have outlined above [here](https://github.com/adaptlearning/adapt-contrib-languagePicker/pull/57)

It will require a framework dependency bump to fetch the 'availableLanguageNames' from adapt.build

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Comment by oliverfoster** [comment]
closed in favour of #57

**Pull request closed without merging**
